### PR TITLE
Fixes for mid-row codes, field 2 captions, special/extended chars

### PR DESCRIPTION
**Pull request by squarebracket**
Some things were not properly implemented according to the CEA608 spec.

1. Mid-row codes were not inserting a space, which they must.
2. Not all duplicate control characters were dropped, causing special
   and extended characters to be doubled up on the output.
3. Field 2 caption miscellaneous control codes were not being interpreted, causing field 2 captions to not work properly. They are their field one value + 1.

I've had to edit the tests to remove the spaces that were manually
inserted.

### CODE REVIEW

**Comment by TobbeEdgeware** [comment]
Nice PR.

Regarding your first point,  I think it is strange that inserting a mid-row red command inserts a space of the old color, so Reading the spec Section 7.4, it says that "Receipt of a BS shall move the cursor one column to the left, erasing the character or Mid-Row Code occupying that location." 

Is it possible to use a BS to get a new mode with mid-row command without a space, or is it simply not possible?

If possible, I'd like to keep a test vector without a space in the old mode.

**Comment by squarebracket** [comment]
Also from 7.4
> The cursor moves automatically one column to the right after each character or Mid-Row Code received.

Think of it like this. A mid-row code is a single character that occupies a single column in memory. That character cannot be displayed, and so it is rendered as a space. However, that single character does affect the formatting for the rest of the row. Thus, when backspacing, you remove a space from the screen, but you also delete the attributes of the mid-row code.

This agrees with what's stated in C.7:
> If, when a displayable character is received, it overwrites an existing PAC or mid-row code, and there are already characters to the right of the new character, these existing characters shall assume the same attributes as the new character. This adoption can result in a whole caption row suddenly changing color, underline, italics, and/or flash attributes.

All this to say, no, it is not possible to have a mid-row code _without_ a space, since the mid-row code _is_ the space. Remove or replace the space, and you remove or replace the mid-row code.

It's probably worth pointing out that the behaviour described above doesn't actually happen in the code. Mid-row codes are treated as literal spaces and so if you backspace over a mid-row code, the previous column's formatting won't be applied to the rest of the row. If you think that should be done, I can add that on to this PR.

As for what you ask about the test, I don't understand what you mean. Are you saying you'd like there to be spaces inside the caption data, and thus have two spaces in the output/`<test>.vtt` file?

**Comment by TobbeEdgeware** [comment]
@squarebracket Thanks for the explanation. I now understand that it is not possible to achieve a change from a green non-space character to a yellow non-space character using a midrow code.

Having a backspace undoing a midrow code would be nice, but it's a corner case, so I'm fine with leaving it as it is.

**Comment by squarebracket** [comment]
Sounds good, less work for me :)

**Pull request merged**
